field: f7f5703c-a5d1-4ece-81f6-cd69aacba8cb
fieldLayouts:
  4461f21f-abb8-4816-8013-0f3970460f78:
    tabs:
      -
        elements:
          -
            fieldUid: c7fd47c1-7147-466b-9710-16b4d5d9c0e2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 97134205-e4b8-4169-a51b-ca23329ec35a
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  97134205-e4b8-4169-a51b-ca23329ec35a:
    contentColumnType: string
    fieldGroup: null
    handle: productInfo
    instructions: ''
    name: 'Product Info'
    searchable: false
    settings:
      defaultDimensionsUnit: centimeters
      defaultHeight: ''
      defaultLength: ''
      defaultShippable: '1'
      defaultTaxable: '1'
      defaultWeight: ''
      defaultWeightUnit: grams
      defaultWidth: ''
      displayInventory: '1'
      displayShippableSwitch: '1'
      displayTaxableSwitch: '1'
      skuDefault: ''
    translationKeyFormat: null
    translationMethod: none
    type: fostercommerce\snipcart\fields\ProductDetails
  c7fd47c1-7147-466b-9710-16b4d5d9c0e2:
    contentColumnType: text
    fieldGroup: null
    handle: productName
    instructions: ''
    name: 'Product Name'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: product
name: Product
sortOrder: 2
