contentColumnType: string
fieldGroup: d07e3821-ffb4-4407-80a2-06f84b0e7d97
handle: productDetails
instructions: 'Define product details here.'
name: 'Product Details'
searchable: false
settings:
  defaultDimensionsUnit: inches
  defaultHeight: null
  defaultLength: null
  defaultShippable: true
  defaultTaxable: true
  defaultWeight: null
  defaultWeightUnit: pounds
  defaultWidth: null
  displayInventory: true
  displayShippableSwitch: true
  displayTaxableSwitch: true
  skuDefault: ''
translationKeyFormat: null
translationMethod: none
type: workingconcept\snipcart\fields\ProductDetails
